name: Create Release Branches
run-name: Create Release Branches for ${{ inputs.release_file }}

on:
  workflow_call:
    inputs:
      release_file:
        required: true
        type: string
    secrets:
      release_bot_token:
        required: true

jobs:
  parse:
    name: Parse ${{ inputs.release_file }}
    uses: ./.github/workflows/parse-release.yml
    with:
      release_file: ${{ inputs.release_file }}

  create:
    name: Create Branch - ${{ matrix.release_repo }}
    needs: parse
    strategy:
      matrix:
        release_repo: ${{ fromJson(needs.parse.outputs.release_repos) }}
    uses: ./.github/workflows/create-release-branch-for-repo.yml
    with:
      repo: ${{ matrix.release_repo }}
      version: ${{ needs.parse.outputs.release_version }}
    secrets:
      release_bot_token: ${{ secrets.release_bot_token }}
