name: Create Release Tags
run-name: Create Release Tags for ${{ inputs.tag_file }}

on:
  workflow_call:
    inputs:
      tag_file:
        required: true
        type: string
    secrets:
      release_bot_token:
        required: true

jobs:
  parse:
    uses: ./.github/workflows/parse-tag.yml
    with:
      tag_file: ${{ inputs.tag_file }}

  create_tags:
    needs: parse
    strategy:
      matrix:
        release_repo: ${{ fromJson(needs.parse.outputs.release_repos) }}
    uses: ./.github/workflows/create-tag-for-repo.yml
    with:
      repo: ${{ matrix.release_repo }}
      release_branch: ${{ needs.parse.outputs.release_version }}
      tag_version: ${{ needs.parse.outputs.tag_version }}
    secrets:
      release_bot_token: ${{ secrets.release_bot_token }}
