name: Release
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6
        with:
          distribution: goreleaser-pro
          version: latest
          args: check ./goreleaser/base.yml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
