name: Release
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: latest
          args: check ./goreleaser/base.yml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
