name: linters

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  yaml-lint:
    name: yaml lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Run yamllint on release files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: releases/**/*.yml
